name: Sync Docs and Wiki

on:
  push:
    paths:
      - "docs/**"
  workflow_dispatch:
  repository_dispatch:
    types: [docs]

  
env:
    docs: ./main/docs
    wiki: ./wiki
    #suffix: [github-actions-bot]


jobs:   
  sync:
    name: Sync Docs to Wiki
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v3
        with:
          path: main
          #token: ${{env.token}}
      - name: Checkout Wiki Repo
        uses: actions/checkout@v3
        with:
          path: wiki
          repository: ${{github.repository}}.wiki
          #token: ${{env.token}}
      - name: Get Commit Author
        id: get-author
        working-directory: ${{env.docs}}
        run: echo "AUTHOR=$(git log -1 --format="%an")" >> $GITHUB_OUTPUT
      - name: Get Commit Email
        id: get-email
        working-directory: ${{env.docs}}
        run: echo "EMAIL=$(git log -1 --format="%ae")" >> $GITHUB_OUTPUT
      - name: Print Commit Message
        working-directory: ${{env.docs}}
        run: echo "$(git log -1 --format="%B")"
      - name: Get Commit Message
        id: get-message
        working-directory: ${{env.docs}}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "MESSAGE<<$EOF" >> "$GITHUB_OUTPUT"
          git log -1 --format="%B" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
      - name: Get Source Commit Subject
        id: get-src-sub
        working-directory: ${{env.docs}}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "SUB<<$EOF" >> "$GITHUB_OUTPUT"
          git log -1 --format="%s" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
      - name: Get Destination Commit Subject
        id: get-dst-sub
        working-directory: ${{env.wiki}}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "SUB<<$EOF" >> "$GITHUB_OUTPUT"
          git log -1 --format="%s" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
      - name: Preprocess and Refactor Files
        working-directory: ${{env.docs}}
        run: |
          chmod +x ../.github/actions/wiki_sync/refactor.sh
          ../.github/actions/wiki_sync/refactor.sh
        shell: bash
      - name: Copy Doc Files to Wiki
        run: |
          rsync -avzr --delete --exclude='.git/' "${{env.docs}}/" "${{env.wiki}}/"
      - name: Push
        working-directory: ${{env.wiki}}
        run: |
          #export GIT_AUTHOR_NAME="github-actions[bot]"
          #export GIT_AUTHOR_EMAIL="41898282+github-actions[bot]@users.noreply.github.com"
          #export GIT_COMMITTER_NAME="${{ steps.get-author.outputs.AUTHOR }}"
          #export GIT_COMMITTER_EMAIL="${{ steps.get-email.outputs.EMAIL }}"
          export GIT_AUTHOR_NAME="${{ steps.get-author.outputs.AUTHOR }}"
          export GIT_AUTHOR_EMAIL="${{ steps.get-email.outputs.EMAIL }}"
          export GIT_COMMITTER_NAME="github-actions[bot]"
          export GIT_COMMITTER_EMAIL="41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if [ "${{ steps.get-src-sub.outputs.SUB }}" = "${{ steps.get-dst-sub.outputs.SUB }}"]; then
            git commit --amend --no-edit
            git push --force-with-lease
          else
            git commit -m "${{ steps.get-message.outputs.MESSAGE }}"
            git push
          fi
